apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/divyasuranjan/snapshot-shortlink-api
    newTag: latest
  - name: ghcr.io/divyasuranjan/snapshot-analytics-worker
    newTag: latest
  - name: ghcr.io/divyasuranjan/snapshot-dashboard
    newTag: latest
