apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/divyasuranjan/snapshot-analytics-worker
  newTag: aa05d299a05018247d510b44b5cc35727f69f734
- name: ghcr.io/divyasuranjan/snapshot-dashboard
  newTag: aa05d299a05018247d510b44b5cc35727f69f734
- name: ghcr.io/divyasuranjan/snapshot-shortlink-api
  newTag: latest
